[tool.poetry]
name = "scratch"
version = "0.1.0"
description = "a bunch of junk"
authors = ["dan <dan@omadi.com>"]
license = "anyone anytime"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
